<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RazorCompileOnBuild>false</RazorCompileOnBuild>
    <RazorCompileOnPublish>false</RazorCompileOnPublish>
    <CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
    <CompressionEnabled>false</CompressionEnabled><!-- Disable compression. E.g. for umbraco backoffice files. These files should be precompressed by node and not let dotnet handle it -->
  </PropertyGroup>
<ItemGroup>
    <ProjectReference Include="..\Demo.Backoffice\Demo.Backoffice.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Clean" Version="6.0.1" />
    <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="72.1.0.3" />
    <PackageReference Include="Umbraco.Cms" Version="17.0.0-beta" />
    <PackageReference Include="Umbraco.Cms.DevelopmentMode.Backoffice" Version="17.0.0-beta" />
    <PackageReference Include="uSync" Version="17.0.0-beta" />
  </ItemGroup>
  <ItemGroup>
    <!-- Opt-in to app-local ICU to ensure consistent globalization APIs across different platforms -->
    <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="72.1.0.3" Condition="$(RuntimeIdentifier.StartsWith('linux')) or $(RuntimeIdentifier.StartsWith('win')) or ('$(RuntimeIdentifier)' == '' and !$([MSBuild]::IsOSPlatform('osx')))" />
  </ItemGroup>
</Project>